[tox]
envlist =
    py310
    docs
skip_missing_interpreters=true

[testenv]
deps =
    -r requirements/tests.txt
commands =
    coverage run -m pytest
    coverage report

[testenv:docs]
deps =
    -r requirements/docs.txt
changedir = docs
commands = sphinx-build -W -b html -d {envtmpdir}/doctrees . {envtmpdir}/html
