name: Docs
on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.9'
      - name: install dependencies
        run: |
          pip install tox
      - name: build docs
        run: tox -e docs
